version: '3.1'

services:

  apache:
    build: ./apache
    restart: always
    ports:
      - 8000:80

  ads:
    build: ./ads
    restart: always

  articles:
    build: ./articles-crud
    restart: always

  auth:
    build: ./auth
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./frontend:/app
